### PR TITLE
GHC 8.10 on nixos-unstable

### PR DESCRIPTION
**Pull request by nh2**
Extracted from https://github.com/nh2/static-haskell-nix/pull/98#discussion_r672985880

---

CC @int-index

### CODE REVIEW

**Comment by int-index** [comment]
Is there a commit that would incorporate https://github.com/NixOS/nixpkgs/pull/128746 also? I’m interested in building SDL

**Comment by nh2** [comment]
> Is there a commit that would incorporate [NixOS/nixpkgs#128746](https://github.com/NixOS/nixpkgs/pull/128746) also? I’m interested in building SDL

@int-index It seems there isn't, that's only on `staging`, not `master` yet: https://nixpk.gs/pr-tracker.html?pr=128746

You can cherry-pick it of course, but there will be a lot of stuff to rebuild.

**Comment by nh2** [comment]
@int-index But you can add it here meanwhile, if you want to override the version just for your static builds:

https://github.com/nh2/static-haskell-nix/blob/217a812de7387d3f056cc6fc4d861f52d6afa3ca/survey/default.nix#L598

**Comment by nh2** [comment]
CI is green, merging.

**Pull request merged**
